disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Studio uni-yo-kan"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2006/01/02"
logo = "logo_studio_uni_yokan.png"
description = "個人開発をしています"

  [params.author]
  name = "uni-yo-kan"
  image = "uni_yo_kan.png"
  headline = "個人開発をしています"
  bio = ""
  links = [ ]
