[[main]]
name = "home"
pageRef = "/"
identifier = "home"
weight = 0

[[main]]
name = "work"
pageRef = "categories/app"
identifier = "LAtnJhmcEi"
weight = 1

[[main]]
name = "posts"
pageRef = "posts"
identifier = "posts"
weight = 2

[[main]]
name = "policy"
pageRef = "policy"
identifier = "UGh7W56yuc"
weight = 10

[[main]]
name = ""
pre = "x"
url = "https://x.com/uni_yo_kan"
identifier = "DwCVpwVQgZ"
weight = 9991

[[footer]]
none = "none"
