[[main]]
none = "none"

[[main]]
name = "work"
pageRef = "work"
identifier = "LAtnJhmcEi"
weight = 1

[[main]]
name = "policy"
pageRef = "policy"
identifier = "UGh7W56yuc"
weight = 2

[[main]]
name = ""
pre = "x"
url = "https://x.com/uni_yo_kan"
identifier = "DwCVpwVQgZ"
weight = 3

[[main]]
name = "zenn"
pre = "zenn"
url = "https://zenn.dev/uni_yo_kan"
identifier = "Hsb7xKYSfx"
weight = 4

[[footer]]
none = "none"
